package couk.psyked.pixelbender
{

	import flash.display.Shader;
	import flash.display.ShaderParameter;
	import flash.utils.ByteArray;

	/**
	 * Generated by PBJtoAS http://blog.minim.pl/PBJtoAS
	 *
	 * namespace : idv.cjcat.pixelbender
	 * vendor : Allen Chou
	 * version : 1
	 * description : 5-level motion blur.
	 */

	public dynamic class MotionblurShader extends Shader
	{

		static private var instance:MotionblurShader;

		private var data2:Object;

		public function MotionblurShader()
		{
			var ba:ByteArray = new ByteArray();
			var bytes:Array = 'F85A6DD23DCE43B098BCBBCE 5D0D03323CA6181282092B3E93B30A0A6D841CD8C84B9C915BFF56C23347C6CFD84AA313071AA28AF4067249295D2199970F23E7B6E6E7360978660F99767E9912549C017594CC9E42C72318C9422306A868F 1AC3A63E82274C8A5214AB0F3AA3A24997ADA2B449B5E27A5E6BB154AF22A8023F92872A0 B462692A7 7DAD5CAFBF13D419B51 AAE66 C834E75C5D98C53B48B 953BB38 C53B2A9704862A839123AD4B0 7281CB4F4F0E6E828EEE529 BC67249D12719CC6E347AA56C3F37BFFE 44DF9 2483380F3AE985AE1DE4031B085DE516118DAE4587B667EA66FD975F2F02B51E96E99E9A36F563A85411B7992F051A31F49913A27646C88ACB996B890F8DB779C8B63E32687867DB5FAEBF48DD2 E66D3 35264ADC2E1F45B7439E0 482B7B8EA6153B61CE155427ED6BF5F62E77FFB7E741E1E 05F271FA1EC2C84AEE111EE137E85E8A928CA'.split( '' );
			var i:uint = 0;

			while ( bytes.length )
			{
				ba.position = i;
				ba.writeByte( parseInt( bytes.shift() + bytes.shift(), 16 ) - 128 );
				i++;
			}
			ba.uncompress();

			super( ba );
			data2 = this[ 'data' ];
		}

		public function setDefaultParameters():void
		{
			var j:uint;

			for ( var i:String in data2 )
			{
				if ( data2[ i ] is ShaderParameter )
				{
					if ( data2[ i ].value[ 0 ] is Array )
					{
						for ( j = 0; j < data2[ i ].value.length; j++ )
						{
							ShaderParameter( data2[ i ]).value[ j ] = ShaderParameter( data2[ i ])[ 'defaultValue' ][ j ].concat();
						}
					}
					else
					{
						ShaderParameter( data2[ i ]).value = ShaderParameter( data2[ i ])[ 'defaultValue' ].concat();
					}
				}
			}
		}

		public function get amount():Number
		{
			return Number( data2.amount.value[ 0 ]);
		}

		/**
		 * @param float_ from 0 to 50
		 */
		public function set amount( float_:Number ):void
		{
			data2.amount.value[ 0 ] = float_;
		}

		public function get angle():Number
		{
			return Number( data2.angle.value[ 0 ]);
		}

		/**
		 * @param float_ from 0 to 6.283180236816406
		 */
		public function set angle( float_:Number ):void
		{
			data2.angle.value[ 0 ] = float_;
		}

		static public function getInstance():MotionblurShader
		{
			if ( instance )
			{
				return instance;
			}
			else
			{
				instance = new MotionblurShader();
				return instance;
			}
		}
	}
}