package couk.psyked.pixelbender
{

	import flash.display.Shader;
	import flash.display.ShaderParameter;
	import flash.utils.ByteArray;

	/**
	 * Generated by PBJtoAS http://blog.minim.pl/PBJtoAS
	 *
	 * namespace : com.rphelan
	 * vendor : Ryan Phelan
	 * version : 1
	 * description : Applies a sharpen effect to an image.
	 */

	public dynamic class SharpenShader extends Shader
	{

		static private var instance:SharpenShader;

		private var data2:Object;

		public function SharpenShader()
		{
			var ba:ByteArray = new ByteArray();
			var bytes:Array = 'F85AFD10CBCA83C190 67F6E1ED7A0E016 28C748982F1AF92BC 062422DB4B39DB310F9B0 F203B9CA57131F115A318FD3C 4B710DC40AA2685D1F0B645DF7F77D77554 B80709C22191B3A3245FAD8185CB615C9AC12B29F57555CAECC 175F0E9 B342CF17DE08AFD651A515256CDD69690842436C96A2CEAD9CF2BEA1159C69B6D66EABB1B592455ED29A91F65664E E319192985EDEF66DC5D956A9E9FA CB4F95995AD9EC51E95B7E651D970C7525C77F23AE6195A196996ED5FBADF21CF B5A24D9577C13E674D77AEC3FFFFF 2575489B65293B8CA1B9631448E98E12270A929469E8E8AA7 885BEBC9C332F 1B71CAA2CF8856911622A301358F2DF3B3EE6 4FD66491F30CFFA42ADA9F9856D71F98F75839CFC5A2328822F 8FD9C825E6BF8714D87 E8FFBDF 5 E27DC78 36F67EFB1899D9F753E A9CCF39684FFC62A3478FFADF8D9CCF3981E93A76C7C8F710D4A32A2CFD27833E F4048237F7D82DB39 4CC'.split( '' );
			var i:uint = 0;

			while ( bytes.length )
			{
				ba.position = i;
				ba.writeByte( parseInt( bytes.shift() + bytes.shift(), 16 ) - 128 );
				i++;
			}
			ba.uncompress();

			super( ba );
			data2 = this[ 'data' ];
		}

		public function setDefaultParameters():void
		{
			var j:uint;

			for ( var i:String in data2 )
			{
				if ( data2[ i ] is ShaderParameter )
				{
					if ( data2[ i ].value[ 0 ] is Array )
					{
						for ( j = 0; j < data2[ i ].value.length; j++ )
						{
							ShaderParameter( data2[ i ]).value[ j ] = ShaderParameter( data2[ i ])[ 'defaultValue' ][ j ].concat();
						}
					}
					else
					{
						ShaderParameter( data2[ i ]).value = ShaderParameter( data2[ i ])[ 'defaultValue' ].concat();
					}
				}
			}
		}

		public function get radius():Number
		{
			return Number( data2.radius.value[ 0 ]);
		}

		/**
		 * @param float_ from 0 to 1
		 */
		public function set radius( float_:Number ):void
		{
			data2.radius.value[ 0 ] = float_;
		}

		public function get amount():Number
		{
			return Number( data2.amount.value[ 0 ]);
		}

		/**
		 * @param float_ from 0 to 20
		 */
		public function set amount( float_:Number ):void
		{
			data2.amount.value[ 0 ] = float_;
		}

		static public function getInstance():SharpenShader
		{
			if ( instance )
			{
				return instance;
			}
			else
			{
				instance = new SharpenShader();
				return instance;
			}
		}
	}
}