package couk.psyked.pixelbender
{

	import flash.display.Shader;
	import flash.display.ShaderParameter;
	import flash.utils.ByteArray;

	/**
	 * Generated by PBJtoAS http://blog.minim.pl/PBJtoAS
	 *
	 * namespace : com.rphelan
	 * vendor : Ryan Phelan
	 * version : 1
	 * description : Projects an image onto a rippled surface of water
	 */

	public dynamic class WavereflectionShader extends Shader
	{

		static private var instance:WavereflectionShader;

		private var data2:Object;

		public function WavereflectionShader()
		{
			var ba:ByteArray = new ByteArray();
			var bytes:Array = 'F85A15114DCA43C094 54FA4DD94A95A 5BBA94C93 8F4DF8D3AF0E969C217BAA4B7B512E4521924DA5C74D1DAFF40154FA038926A43 83877CEDB31F4A19886AE675E6F1EB3C39E85 0 7CD1C29A175A8CEA9AC931DCF9A394A4896AAA4 4BA5BB545A525AA4724B124BC52863D114AE5F7592C8F49D85E 2E0A0A29B1A24F0AE689AFD45 6D6B21CE42ACFD2672516CAB2D02494C9DB1918B324 E6535AA49E0AABC20F1FED215C7DA1B 8B55F4FAB C6E9B3296F7A2CB72D315D6847731D4B78BF9B0F6B222D8D5E979CB4C77 54A AB4A92B 87EE7307F74754A86827558502022BC9C7DE53051992C9B286367FB542C89B175EA9E36A2DB22A520 0A65A82CD975A72B196F8 14795FCF85E94DCBD2EBEC73439FF7836FD4BDC60B4F3 17BE9BFFBBED7EE213142F7E633F747E3B11F6F2D73AB7941B2BF904BFC477B739A 05FAF5DFC4F47 74085DA9EBEFD6C609B9860 D36'.split( '' );
			var i:uint = 0;

			while ( bytes.length )
			{
				ba.position = i;
				ba.writeByte( parseInt( bytes.shift() + bytes.shift(), 16 ) - 128 );
				i++;
			}
			ba.uncompress();

			super( ba );
			data2 = this[ 'data' ];
		}

		public function setDefaultParameters():void
		{
			var j:uint;

			for ( var i:String in data2 )
			{
				if ( data2[ i ] is ShaderParameter )
				{
					if ( data2[ i ].value[ 0 ] is Array )
					{
						for ( j = 0; j < data2[ i ].value.length; j++ )
						{
							ShaderParameter( data2[ i ]).value[ j ] = ShaderParameter( data2[ i ])[ 'defaultValue' ][ j ].concat();
						}
					}
					else
					{
						ShaderParameter( data2[ i ]).value = ShaderParameter( data2[ i ])[ 'defaultValue' ].concat();
					}
				}
			}
		}

		public function get amplitude():Number
		{
			return Number( data2.amplitude.value[ 0 ]);
		}

		/**
		 * @param float_ from 0 to 1
		 */
		public function set amplitude( float_:Number ):void
		{
			data2.amplitude.value[ 0 ] = float_;
		}

		public function get progress():Number
		{
			return Number( data2.progress.value[ 0 ]);
		}

		/**
		 * @param float_ from 0 to 1
		 */
		public function set progress( float_:Number ):void
		{
			data2.progress.value[ 0 ] = float_;
		}

		public function get frequency():Number
		{
			return Number( data2.frequency.value[ 0 ]);
		}

		/**
		 * @param float_ from 0 to 0.5400000214576721
		 */
		public function set frequency( float_:Number ):void
		{
			data2.frequency.value[ 0 ] = float_;
		}

		static public function getInstance():WavereflectionShader
		{
			if ( instance )
			{
				return instance;
			}
			else
			{
				instance = new WavereflectionShader();
				return instance;
			}
		}
	}
}